### ISSUE TITLE
[Bug] Player Level isn't being updated or exp points

### ISSUE THREAD

**Issue by Vvnguyen25** [LLAMARPG/game#52] opened 2024-06-20 04:28 UTC
Not sure if 60 is the max level. But I leveled up and got extra stat points but the player level or amount of exp did not update.

Before battle at level 60.
![image](https://github.com/LLAMARPG/game/assets/172426161/8329b67c-b1e7-4cf7-b6f7-98f05f4df55e)

Gained a level but still at 60.
![image](https://github.com/LLAMARPG/game/assets/172426161/6e26cfce-9a38-4763-8b95-57c411580391)

**Comment by Warren1001** [comment] 2024-06-20 04:30
duplicate of #29 , fixed in the current dev build

**Closed by Warren1001** 2024-06-20 04:30 UTC
Labels: bug
